openapi: 3.0.0 

info:
  title: "Shoe REST API"
  description: "REST API for shoe store with Python Flask on backend"
  version: "1.0.0"

servers:
  - url: "/shoe-api"

components:
  schemas:
    Shoe:
      type: "object"
      required:
        - name
        - shoe_size
        - shoe_type
        - colour
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        desc:
          type: "string"
        shoe_size:
          type: "integer"
        shoe_type:
          type: "string"
        gender:
          type: "string"
        colour:
          type: "string"
  parameters:
    name:
      name: "name"
      description: "shoe name"
      in: path
      required: True
      schema:
        type: "string"
        

paths:
  /shoe/{name}:
    get:
      operationId: "shoe_shared.services.ShoeService.get_shoe"
      tags:
        - "Shoes"
      summary: "Get specific shoe"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: "Successfully retrieved the shoe"
    put:
      tags:
        - "Shoes"
      operationId: "shoe_shared.services.ShoeService.edit_shoe"
      summary: "Update a shoe"
      parameters:
        - $ref: "#/components/parameters/name"
      requestBody:
        description: "Shoe data to update"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "new_shoe"
              $ref: "#/components/schemas/Shoe"
      responses:
        "200":
          description: "Successfully updated shoe"

    delete:
      tags:
        - "Shoes"
      operationId: "shoe_shared.services.ShoeService.delete_shoe"
      summary: "Delete a shoe"
      parameters:
        - $ref: "#/components/parameters/name"
      responses:
        "204":
          description: "Successfully deleted shoe"
          

  /shoes:
    get:
      operationId: "shoe_shared.services.ShoeService.read_all"
      tags:
        - "Shoes"
      summary: "Read the list of shoes"
      responses:
        "200":
          description: "Successfully read shoes list" 
    
    post:
      operationId: "shoe_shared.services.ShoeService.add_shoe"
      tags:
        - "Shoes"
      summary: "Add new shoe"
      requestBody:
        description: "Shoe to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "shoe"
              $ref: "#/components/schemas/Shoe"
      responses:
        "201":
          description: "Successfully added shoe"

    